service: gusto

layers:
  ${file(layers.yml)}

resources:
  Resources:
    GustoPayrollBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: gusto-dev-payrolls

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
        - secretsmanager:PutSecretValue
        - s3:PutObject
        - s3:ListBucket
        - s3:CreateBucket
        - s3:ListAllMyBuckets
      Resource: '*'


functions:
  create_company:
    handler: create_company.main
    module: app/functions
    events:
      - http:
          path: /create_company
          method: post
    package:
      include:
        - app/functions/create_copmany.py

#  companies:
#    handler: companies.main
#    module: app/functions
#    events:
#      - http:
#          path: /companies
#          method: get
#    package:
#      include:
#        - app/functions/companies.py

  initial_auth:
    handler: initial_auth.main
    module: app/functions
    events:
      - http:
          path: /initial_auth
          method: get
    package:
      include:
        - app/functions/initial_auth.py

  auth:
    handler: auth.main
    module: app/functions
    events:
      - http:
          path: /auth
          method: post
    package:
      include:
        - app/functions/auth.py

  payrolls:
    handler: payrolls.main
    environment:
      BUCKET: ${self:resources.Resources.GustoPayrollBucket.Properties.BucketName}
    module: app/functions
    events:
      - http:
          path: /payrolls
          method: post
    package:
      include:
        - app/functions/payrolls.py
    layers:
      - {Ref: AuthenticateLambdaLayer}

  payrolls_test:
    handler: payrolls_test.main
    environment:
      BUCKET: ${self:resources.Resources.GustoPayrollBucket.Properties.BucketName}
#      REGION: us-west-1
    module: app/functions
    events:
      - http:
          path: /payrolls_test
          method: post
    package:
      include:
        - app/functions/payrolls_test.py

  employees:
    handler: employees.main
    module: app/functions
    events:
      - http:
          path: /employees
          method: post
    package:
      include:
        - app/functions/employees.py
    layers:
      - {Ref: AuthenticateLambdaLayer}

plugins:
  - serverless-python-requirements
package:
  individually: true

